[package]
name = "sourceweaver-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "sourceweaver"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sourceweaver-core = { path = "../sourceweaver-core" }
toml = "0.8"
ureq = "2"
